pipeline:
  build:
    image: docker
    commands:
      - docker build -t ${IMAGE_NAME} .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push
      branch: master

  publish:
    image: plugins/ecr
    repo: ${ECR_REPO}
    registry: ${ECR_REGISTRY}
    secrets: [ ecr_access_key, ecr_secret_key ]
    tags: ${TAGS}
    when:
      event: push
      branch: master

  slack:
    image: plugins/slack
    webhook: ${SLACK_WEBHOOK}
    channel: ${SLACK_CHANNEL}
    username: ${SLACK_USER}
    when:
      status: [ success, failure ]

matrix:
  IMAGE_NAME:
    - examples/microtrader-base
  TAGS:
    - latest
    - 1.0
  ECR_REPO:
    - 685721039798.dkr.ecr.us-east-1.amazonaws.com/examples/microtrader-base
  ECR_REGISTRY:
    - 685721039798.dkr.ecr.us-east-1.amazonaws.com
  SLACK_WEBHOOK:
    - https://hooks.slack.com/services/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
  SLACK_CHANNEL:
    - ci-messages
  SLACK_USER:
    - drone